# Generated by Django 5.2.3 on 2025-08-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStampedModel',
        ),
    ]
